# Generated by Django 4.1.7 on 2023-04-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_veiculo_cliente_id_alter_veiculo_fabricante_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rotatitvo',
            new_name='Rotativo',
        ),
    ]
